#title: AVERtek # your name photo (or website title) here
logo1: "images/Company Here.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2><b>CELEBRATE YOUR TEAM</h2></b>
  <h3><b>Share Your Fan-Kit</h3></b>
  <br><br>
  <b>GEAR UP:</b><a href="https://bit.ly/3vWuhDY" onclick="getOutboundLink('https://bit.ly/3vWuhDY'); return false;"</b><b> MLB Fan's Here</b></a>
  <br><br> 
  <b>CATCH A GAME:</b><a href="https://binged.it/3cgXodx" onclick="getOutboundLink('https://binged.it/3cgXodx'); return false;"</b><b> 2021 MLB Schedule</b></a>
  <br><br>
  <b>BUY TICKETS:</b><a href="https://bit.ly/3tRcpsn" onclick="getOutboundLink('https://bit.ly/3tRcpsn'); return false;"</b><b> Quick & Easy</b></a>
  <br><br>
  <b>EXPLORE (YOUR COMPANY):</b><a href="https://avertek.net/" onclick="getOutboundLink('https://avertek.net/'); return false;"</b><b> Augmented Reality Marketing</b></a> 
  <br><br>
  <b>DISCOVER MORE:</b><a href="https://avertek.net/contact-us" onclick="getOutboundLink('https://avertek.net/contact-us'); return false;"</b> <b> Contact Us</a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-000000000-0 
